name: Prod Deploy

on: 
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - 'json_examples/**'
      - 'models/**'
      - .github/workflows/staging-deploy.yaml


  jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

