name: Staging Deploy

on: 
  pull_request:
    paths-ignore:
      - README.md
      - 'json_examples/**'
      - 'models/**'
      - .github/workflows/prod-deploy.yaml
      - fly.toml


jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

